# dataset_name : 'Camelyon16'
# label_file : 'CAMELYON16.csv'
# src_folder : '/pool1/data/Extracted_IMAGES/Camelyon16/patches/'
# xml_folder : '/data/data/C16_annotations/training/lesion_annotations'
# dst_file: '/data/data/CluBYOL_R18.pkl'


# dataset_name : 'Camelyon16'
# label_file : 'CAMELYON16.csv'
# src_folder : '/pool1/data/Extracted_IMAGES/Camelyon16/patches/'
# xml_folder : '/data/data/C16_annotations/training/lesion_annotations'
# dst_file: '/data/data/New_CluBYOL_R18.pkl'


dataset_name : 'Camelyon16'
label_file : 'CAMELYON16.csv'
src_folder : '/pool1/data/Extracted_IMAGES/Camelyon16/patches/'
xml_folder : '/data/data/C16_annotations/training/lesion_annotations'
dst_file: '/data/data/CluBYOL_R50MOD.pkl'
ckpt_path: '/data/checkpoints/b512_r50_clubyol_49.pth.tar'