# dataset_name : 'Camelyon16'
# label_file : 'CAMELYON16.csv'
# src_folder : '/pool1/data/Extracted_IMAGES/Camelyon16_test/patches/'
# xml_folder : '/data/data/C16_annotations/testing/lesion_annotations'
# dst_file: '/data/data/C16_DINOv2_test.pkl'


dataset_name : 'Camelyon16'
label_file : 'CAMELYON16.csv'
src_folder : '/pool1/data/Extracted_IMAGES/Camelyon16_test/patches/'
xml_folder : '/data/data/C16_annotations/testing/lesion_annotations'
dst_file: '/data/data/CluBYOLR50_C16_test.pkl'
ckpt_path: '/data/checkpoints/b512_CluBYOL_R50_C16_49.pth.tar'