# dataset_name : 'Camelyon16'
# label_file : 'CAMELYON16.csv'
# src_folder : '/pool1/data/Extracted_IMAGES/Camelyon16_test/patches/'
# xml_folder : '/data/data/C16_annotations/testing/lesion_annotations'
# dst_file: '/data/data/CluBYOL_R18_test.pkl'


# dataset_name : 'Camelyon16'
# label_file : 'CAMELYON16.csv'
# src_folder : '/pool1/data/Extracted_IMAGES/Camelyon16_test/patches/'
# xml_folder : '/data/data/C16_annotations/testing/lesion_annotations'
# dst_file: '/data/data/New_CluBYOL_R18_test.pkl'

dataset_name : 'Camelyon16'
label_file : 'CAMELYON16.csv'
src_folder : '/pool1/data/Extracted_IMAGES/Camelyon16_test/patches/'
xml_folder : '/data/data/C16_annotations/testing/lesion_annotations'
dst_file: '/data/data/CluBYOL_R50MOD_test.pkl'
ckpt_path: '/data/checkpoints/b512_r50_clubyol_49.pth.tar'