# dataset_name : 'Camelyon16'
# label_file : 'CAMELYON16.csv'
# src_folder : '/pool1/data/Extracted_IMAGES/Camelyon16_test/patches/'
# xml_folder : '/data/data/C16_annotations/testing/lesion_annotations'
# dst_file: '/data/data/C16_b1024CluBYOLR50_test.pkl'
# ckpt_path: '/data/checkpoints/b1024_CluBYOL_R18_C16_49.pth.tar'


# dataset_name : 'Camelyon16'
# label_file : 'CAMELYON16.csv'
# src_folder : '/pool1/data/Extracted_IMAGES/Camelyon16_test/patches/'
# xml_folder : '/data/data/C16_annotations/testing/lesion_annotations'
# dst_folder: '/data/data/C16_raw/test'


dataset_name : 'Camelyon16'
label_file : 'labels/CAMELYON16.csv'
src_folder : '/pool1/data/Extracted_IMAGES/Camelyon16_test/patches/'
xml_folder : '/data/data/C16_annotations/testing/lesion_annotations'
dst_file: '/data/data/C16_V2_test.pkl'