# label_file : 'TCGA_Lung.csv'
# src_folder : '/data/data/Extracted_IMAGES/TCGA_Lung/patches/'
# # xml_folder : '/media/weiyi/My Passport/Data/CAMELYON16/testing/lesion_annotations'
# dst_file: '/pool1/data/TCGA_Lung_R50.pkl'

dataset_name : 'TCGA_LGG'
label_file : 'labels/TCGA_LGG.csv'
src_folder : '/pool3/data/Extracted_IMAGES/TCGA_LGG_unique/patches/'
# xml_folder : '/media/weiyi/My Passport/Data/CAMELYON16/testing/lesion_annotations'
dst_file: '/pool3/data/TCGA_LGG_unique_UNI'
# ckpt_path: '/data/checkpoints/b512_clubyol_bracs_49.pth.tar'
