dataset_name : 'Yale_HER2'
label_file : 'labels/Yale_HER2.csv'
src_folder : '/data/data/Extracted_IMAGES/Yale_HER2/patches/'
xml_folder : '/data/data/ST/Yale_HER2/Annotations'
dst_file: '/pool2/data/Yale_HER2_PLIP'